buildstatus/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<projectname_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<projectname_id>[0-9]+)/(?P<jobinformation_id>[0-9]+)/$', views.jobdetail, name='job_detail'),
    url(r'^useradmin/$', views.useradmin, name='detail_job'),
    url(r'^author/(?P<pk>\d+)/edit/$', views.post_edit, name='jenkinsjobsinformation_edit'),
    ]

teststatus/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^buildstatus/', include('buildstatus.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

buildstatus/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Projectname(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Jenkinsjobsname(models.Model):
    projectname=models.ForeignKey(Projectname)
    jobsname = models.CharField(max_length=200)
    def __str__(self):
        return self.jobsname

    def get_absolute_url(self):
        return reverse('job_detail',kwargs={'projectname_id': self.projectname.pk, 'jobinformation_id': self.pk})
 

class Jenkinsjobsinformation(models.Model):
    jobinformation=models.ForeignKey(Jenkinsjobsname,on_delete=models.CASCADE,related_name="Jenkinsjobsinformation")
    build = models.IntegerField()
    date = models.DateField(null=True)
    #tag = models.ImageField(upload_to='static/jlr/img/', blank=True)
    Status_choices=(
        ('SUCCESS', 'SUCCESS'),
        ('FAILURE', 'FAILURE'),
    )
    Smoke_choices=(
        ('SUCCESS', 'SUCCESS'),
        ('FAILURE', 'FAILURE'),
    )
    Sanity_choices=(
        ('SUCCESS', 'SUCCESS'),
        ('FAILURE', 'FAILURE'),
    )
    System_choices=(
        ('SUCCESS', 'SUCCESS'),
        ('FAILURE', 'FAILURE'),
    )
    Releasecandidate_choices=(
        ('YES', 'YES'),
        ('NO', 'NO'),
    )
    
    Status=models.CharField(max_length=10,choices=Status_choices,default='SUCCESS')
    Smoke=models.CharField(max_length=10,choices=Smoke_choices,default='SUCCESS')
    Sanity=models.CharField(max_length=100,choices=Sanity_choices,default='SUCCESS')
    System=models.CharField(max_length=100,choices=System_choices,default='SUCCESS')
    Releasecandidate=models.CharField(max_length=100,choices=Releasecandidate_choices,default='YES')
    JIRA_open=models.CharField(max_length=100,null=True)
    JIRA_closed=models.CharField(max_length=100,null=True)

buildstatus/forms.py
from django import forms

from .models import Jenkinsjobsinformation

class PostForm(forms.ModelForm):

    class Meta:
        model = Jenkinsjobsinformation
        fields = ('build', 'date','Status','Sanity','Smoke','System','Releasecandidate','JIRA_open','JIRA_closed')

buildstatus/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404,render

# Create your views here.
from .models import Projectname
from .models import Jenkinsjobsname
from .models import Jenkinsjobsinformation
from django.shortcuts import redirect
import datetime


from .forms import PostForm

from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger


def index(request):
    project_name=Projectname.objects.order_by('name')
    context = {'categories': project_name}
    return render(request,'buildstatus/job_detail.html', context)


def detail(request,projectname_id):
    project_name=Projectname.objects.order_by('name')

    jobs=Projectname.objects.get(pk=projectname_id)

    context = {'jobs': jobs, 'categories':project_name}
    return render(request,'buildstatus/job_detail.html', context)

def jobdetail(request,projectname_id,jobinformation_id):
    project_name=Projectname.objects.order_by('name')

    jobs=Projectname.objects.get(pk=projectname_id)

    
    jobdetail=Jenkinsjobsname.objects.get(pk=jobinformation_id)
    test=jobdetail.Jenkinsjobsinformation.all()

    page = request.GET.get('page',1)
    paginator=Paginator(test,3)# show 3 results per page

    try: 
       results = paginator.page(page)
    except PageNotAnInteger:
       results = paginator.page(1)
    except EmptyPage:
        results=paginator.page(paginator.num_pages)
               
    context = {'jobs': jobs,'categories':project_name,'results':results}
   
    return render(request,'buildstatus/job_detail.html', context)


def post_edit(request,pk):
    jenkinsjobsinformation = get_object_or_404(Jenkinsjobsinformation,pk=pk)
    print request.method
    if request.method == "POST": 
        form = PostForm(request.POST, instance=jenkinsjobsinformation)
        if form.is_valid():
            jenkinsjobsinformation=form.save(commit=True)
            jenkinsjobsinformation.save()
            return redirect('detail_job')
    else:
        form=PostForm(instance=jenkinsjobsinformation)
    return render(request, 'buildstatus/jenkinsjobsinformation_edit.html', {'form': form})

    

def useradmin(request):
    detail=Jenkinsjobsinformation.objects.all()
    page = request.GET.get('page',1)
    paginator=Paginator(detail,5)# show 3 results per page

    try: 
       results = paginator.page(page)
    except PageNotAnInteger:
       results = paginator.page(1)
    except EmptyPage:
        results=paginator.page(paginator.num_pages)
    context= {'results': results}
    return render(request, 'buildstatus/detail_job.html',context)
    
    
    
    

buildstatus/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">
    

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "jlr/dashboard/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "jlr/dashboard/dashboard.css" %}" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Dashboard</a>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/buildstatus/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/login/">Login</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
          <ul class="nav nav-pills flex-column">
            {% block text1 %}
            {% endblock %}
          </ul>
        </nav>

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
          <h1>Dashboard</h1>

          <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <img src="{% static 'jlr/img/release.png' %}" class="img-fluid rounded"  alt="Generic placeholder thumbnail" width="30" height="30">
              <h6>Release candidate</h6>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="{% static 'jlr/img/block.png' %}"class="img-fluid rounded" alt="Generic placeholder thumbnail" width="30" height="30">
              <h6>Build failed or build failed smoke or sanity tests</h6>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="{% static 'jlr/img/thumbs-down.png' %}" class="img-fluid rounded" alt="Generic placeholder thumbnail" width="30" height="30">
              <h6>Not recommended for release</h6>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="{% static 'jlr/img/thumbs-up.png' %}" class="img-fluid rounded" alt="Generic placeholder thumbnail" width="30" height="30">
              <h6>Recommended for further testing</h6>
            </div>
          </section>
           <div class="table-responsive">
            <table class="table table-striped table-bordered">
              <thead>
                  <tr>
                  {% block text %}
                  {% endblock %}
                  </tr>
              </thead>
              <tbody>               
                 {% block text2 %}
                 {% endblock %}               
              </tbody>
            </table>
          </div>
 
        </main>
      </div>
    </div>
    
    <script src="{% static "jlr/dashboard/jquery-3.js" %}"integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>    
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "jlr/dashboard/jquery.min.js" %}"><\/script>')</script>
    <script src="{% static "jlr/dashboard/popper.js" %}"></script>
    <script src="{% static "jlr/dashboard/bootstrap.js" %}"></script>
    <script src="{% static "jlr/dashboard/ie10-viewport-bug-workaround.js" %}"></script>
   
    
</body>
</html>

buildstatus/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      
      <ul class="sidebar-nav">
          <li><a href="/buildstatus/">Home</a></li>
      {% if user.is_authenticated %}
           <li>User: {{ user.get_username }}</li>
           <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
        {% else %}
           <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
      {% endif %} 
      </ul>
      </div>
      <div class="col-sm-10 ">
      {% if user.is_authenticated %}
      {% block content %}{% endblock %}
      {% endif %} 
      </div>
      <div class="col-sm-6 ">     
      {% block text2 %}{% endblock %}
      </div>
    </div>

  </div>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
   <script src=//code.jquery.com/jquery-1.12.4.js></script>
   
   <script type="text/javascript">
    $(document).ready(function() {
    $('#packages_table1').DataTable()
    
} );
    </script>
</body>
</html>

buildstatus/templates/buildstatus/detail_job.html
{% extends "base_generic.html" %}
{% block content %}
<table id="packages_table1" table class = "table table-striped table-bordered" >
        <thead>
                <tr>
                  <th>Build</th>
                  <th>date</th>
                  <th>Status</th>
                  <th>Sanity</th>
                  <th>Smoke</th>
                  <th>System</th>
                  <th>Releasecandidate</th>
                  <th>JIRA_open</th>
                  <th>JIRA_closed</th>
                </tr>
        </thead>
         
    {% for results in results %}
       <tbody>
        <tr> 
            <td>{{ results.build }}</td>
            <td>{{ results.date }}</td>
            <td>{{ results.Status }}</td>
            <td>{{ results.Sanity }}</td>
            <td>{{ results.Smoke }}</td>
            <td>{{ results.System }}</td>
            <td>{{ results.Releasecandidate }}</td>
            <td>{{ results.JIRA_open }}</td> 
            <td>{{ results.JIRA_closed }}</td>       
            <td><a class="btn btn-warning btn-sm js-update-book" href="{% url 'jenkinsjobsinformation_edit' pk=results.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        </tr>
        </tbody>
    {% endfor %}    
</table>
<div class="pagination">
    <span class="step-links">
        {% if results.has_previous %}
            <a href="?page={{ results.previous_page_number }}">PREV</a>
        {% endif %}

        <!--<span class="current">
            Page {{ results.number }} of {{ results.paginator.num_pages }}.
        </span>-->

        {% if results.has_next %}
            <a href="?page={{ results.next_page_number }}">NEXT</a>
        {% endif %}
    </span>
</div>
{% endblock %}

buildstatus/templates/buildstatus/jenkinsjobsinformation_edit.html
{% extends "base_generic.html" %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

buildstatus/templates/buildstatus/job_detail.html
{% extends "base.html" %}

{% block text1 %}
        {% if categories %}    
                {% for category in categories %}
                <li class="nav-item">
                <a class="nav-link" href ="{% url 'detail' category.id %}">{{category.name }}</a>
                </li>
                {% endfor %}            
        {% else %}
            <strong>There are no test categories present.</strong>
        {% endif %}
{% endblock %}



{% block text %} 
    {% for jenkinsjobsname in jobs.jenkinsjobsname_set.all %}       
            <th><a href="{{jenkinsjobsname.get_absolute_url}}">{{jenkinsjobsname.jobsname}}</a></th>        
    {% endfor %}
   
{% endblock %}

{% block text2 %}
<table class = "table table-striped table-bordered">
        <thead>
                <tr>
                  <th>Tag</th>
                  <th>Build</th>
                  <th>date</th>
                  <th>Status</th>
                  <th>Sanity</th>
                  <th>Smoke</th>
                  <th>System</th>
                  <th>Releasecandidate</th>
                  <th>JIRA_open</th>
                  <th>JIRA_closed</th>                  
                </tr>
        </thead>         
    {% for result in results %} 
       <tbody>
        <tr> 
            <td>
                {% if result.Status == "SUCCESS" and result.Sanity == "SUCCESS" and result.Smoke == "SUCCESS" and result.Smoke == "SUCCESS" %}<img src='/static/jlr/img/release.png' class="img-fluid rounded" alt="Generic placeholder thumbnail" width="20" height="20"/>                 	
                {% elif result.Status == "FAILURE" %} <img src='/static/jlr/img/block.png' class="img-fluid rounded" alt="Generic placeholder thumbnail" width="20" height="20"/>
                {% elif result.Releasecandidate == "NO" %}<img src='/static/jlr/img/thumbs-down.png' class="img-fluid rounded" alt="Generic placeholder thumbnail" width="20" height="20"/>
	       {% endif %} </td> 
            <td>{{ result.build }}</td>
            <td>{{ result.date }}</td>
            <td>{{ result.Status }}</td>
            <td>{{ result.Sanity }}</td>
            <td>{{ result.Smoke }}</td>
            <td>{{ result.System }}</td>
            <td>{{ result.Releasecandidate }}</td>
            <td>{{ result.JIRA_open }}</td> 
            <td>{{ result.JIRA_closed }}</td> 
          
        </tr>
       </tbody>
    {% endfor %}   
</table>
<div class="pagination">
    <span class="step-links">
        {% if results.has_previous %}
            <a href="?page={{ results.previous_page_number }}">PREV</a>
        {% endif %}

        <!--<span class="current">
            Page {{ results.number }} of {{ results.paginator.num_pages }}.
        </span>-->

        {% if results.has_next %}
            <a href="?page={{ results.next_page_number }}">NEXT</a>
        {% endif %}
    </span>
</div>
{% endblock %}